name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lambda-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          pip install boto3 pytest
          pytest -q

  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.12.2"
      - run: terraform fmt -check -recursive
      - run: terraform init -backend=false
      - run: terraform validate
